apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: webapp-color-application
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/devopshimanshu/webapp-color-gitops.git
    targetRevision: HEAD
    path: deployment
  destination: 
    server: https://kubernetes.default.svc
    namespace: webapp-color

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true