apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
  namespace: webapp-color
spec:
  selector:
    app: frontend
    env: development
  ports:
    - port: 80
      targetPort: 8080
  externalTrafficPolicy: Local
  type: LoadBalancer